# Generated by Django 5.0.3 on 2024-04-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_id_user_displayname_user_gunfightelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refreshToken',
            field=models.TextField(null=True),
        ),
    ]
