# Generated by Django 5.0.3 on 2024-04-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refreshToken',
        ),
        migrations.AddField(
            model_name='user',
            name='jwt_emitted',
            field=models.IntegerField(default=0),
        ),
    ]
